[tool.poetry]
name = "discordpy-bot-template-with-commands-extension"
version = "0.1.0"
description = ""
authors = ["Raymond Farias <coolweed@epic.com>"]

[tool.poetry.dependencies]
python = "^3.8"
discord = "^2.1.0"
Flask = "^2.2.2"
pytz = "^2022.7"
